export const FETCH_DEVICES = "FETCH_DEVICES";
export const FETCH_DEVICES_SUCCESS = "FETCH_DEVICES_SUCCESS";
export const FETCH_DEVICES_FAILURE = "FETCH_DEVICES_FAILURE";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_REQUEST_SUCCESS = "FETCH_USER_REQUEST_SUCCESS";
export const FETCH_USER_REQUEST_FAILURE = "FETCH_USER_REQUEST_FAILURE";
export const UPDATE_DEVICE_STATUS = "UPDATE_DEVICE_STATUS";
